alter table public.calendar_sync_event_links
add column if not exists id bigint generated by default as identity,
add column if not exists user_id uuid references auth.users (id) on delete cascade,
add column if not exists provider text,
add column if not exists source_type text,
add column if not exists source_record_id text,
add column if not exists source_kind text,
add column if not exists source_id text,
add column if not exists external_calendar_id text,
add column if not exists external_event_id text,
add column if not exists sync_status text default 'pending',
add column if not exists source_updated_at timestamptz,
add column if not exists last_synced_at timestamptz,
add column if not exists last_error text,
add column if not exists created_at timestamptz not null default timezone('utc', now()),
add column if not exists updated_at timestamptz not null default timezone('utc', now());

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'calendar_sync_event_links_provider_check'
  ) then
    alter table public.calendar_sync_event_links
    add constraint calendar_sync_event_links_provider_check
      check (provider in ('google'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'calendar_sync_event_links_source_type_check'
  ) then
    alter table public.calendar_sync_event_links
    add constraint calendar_sync_event_links_source_type_check
      check (source_type in ('appointment', 'todo'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'calendar_sync_event_links_status_check'
  ) then
    alter table public.calendar_sync_event_links
    add constraint calendar_sync_event_links_status_check
      check (sync_status in ('pending', 'synced', 'failed', 'deleted'));
  end if;
end
$$;

create unique index if not exists calendar_sync_event_links_unique_source_idx
on public.calendar_sync_event_links (user_id, provider, source_type, source_record_id);

create index if not exists calendar_sync_event_links_user_idx
on public.calendar_sync_event_links (user_id, provider, sync_status);
